language: node_js
node_js:
  - "6"

install:
  - npm install -g mocha
  - npm install
  - git clone https://github.com/gwuhaolin/spring-data-rest-js-backend.git
  - cd spring-data-rest-js-backend
  - nohup mvn spring-boot:run &
  - sleep 100
  - cd ../
script: mocha

deploy:
  provider: npm
  emial: gwuhaolin@gmail.com
  api_key: "271c2ca1-5c5f-410e-b960-73d614eb9dd5"