language: node_js
node_js:
  - 6

language: java
jdk:
  - oraclejdk8

install:
  - npm install -g mocha
  - git clone https://github.com/gwuhaolin/spring-data-rest-js-backend.git
  - cd spring-data-rest-js-backend
  - nohup mvn spring-boot:run &
  - sleep 100
  - cd ../
script: mocha